'use client';

export function exportToCSV(filename: string, headers: string[], rows: (string | number)[][]) {
  const escape = (v: string | number) => {
    const s = String(v ?? '');
    if (s.includes(',') || s.includes('"') || s.includes('\n')) {
      return `"${s.replace(/"/g, '""')}"`;
    }
    return s;
  };
  const csv = [headers.map(escape).join(','), ...rows.map((r) => r.map(escape).join(','))].join('\n');
  const blob = new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.csv') ? filename : `${filename}.csv`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportToExcel(filename: string, headers: string[], rows: (string | number)[][]) {
  const escape = (v: string | number) => String(v ?? '').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const table = `<table><thead><tr>${headers.map((h) => `<th>${escape(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((r) => `<tr>${r.map((c) => `<td>${escape(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;
  const html = `<html xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="UTF-8"></head><body>${table}</body></html>`;
  const blob = new Blob(['\ufeff', html], { type: 'application/vnd.ms-excel;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename.endsWith('.xls') ? filename : `${filename}.xls`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function printReport(title: string, bodyHTML: string) {
  const w = window.open('', '_blank', 'width=900,height=700');
  if (!w) return;
  w.document.write(`<!DOCTYPE html><html><head><title>${title}</title>
    <style>
      body { font-family: Arial, Helvetica, sans-serif; padding: 24px; color: #1f2937; }
      h1 { font-size: 18px; margin: 0 0 4px; }
      h2 { font-size: 15px; margin: 0 0 4px; }
      .org-header { text-align: center; margin-bottom: 12px; }
      .org-header h1 { font-size: 16px; margin: 0; }
      .org-header p { font-size: 12px; color: #6b7280; margin: 2px 0 0; }
      .meta { color: #6b7280; font-size: 12px; margin-bottom: 16px; }
      table { width: 100%; border-collapse: collapse; font-size: 12px; }
      th, td { padding: 6px 8px; border: 1px solid #e5e7eb; text-align: left; }
      th { background: #f3f4f6; font-weight: 600; }
      .right { text-align: right; }
      .center { text-align: center; }
      .totals { font-weight: 700; background: #f9fafb; }
      .footer { margin-top: 24px; font-size: 11px; color: #6b7280; text-align: center; }
    </style></head><body>${bodyHTML}<div class="footer">Generated by PSKS Accounting ERP &middot; ${new Date().toLocaleString()}</div></body></html>`);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 300);
}
